// <auto-generated />
using System;
using Graduation_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graduation_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graduation_Project.Data.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("SystemId");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("MachineTypes", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineTypeMonitoringAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LowerRange")
                        .HasColumnType("int");

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MonitoringAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("UpperRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("MonitoringAttributeId");

                    b.ToTable("MachineTypeMonitoringAttributes", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineTypeResourceConsumptionAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LowerRange")
                        .HasColumnType("int");

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceConsumptionAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("UpperRange")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("ResourceConsumptionAttributeId");

                    b.ToTable("MachineTypeResourceConsumptionAttribute");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MonitoringAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("MonitoringAttributes", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MonitoringData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("MonitoringAttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("MonitoringAttributeId");

                    b.ToTable("MonitoringData", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.ResourceConsumptionAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("ResourceConsumptionAttributes", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.ResourceConsumptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MachineId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceConsumptionAttributeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ResourceConsumptionAttributeId");

                    b.ToTable("ResourceConsumptionData", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.ToTable("Systems", (string)null);
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.Machine", b =>
                {
                    b.HasOne("Graduation_Project.Data.Models.MachineType", "MachineType")
                        .WithMany("Machines")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Data.Models.System", "System")
                        .WithMany("Machines")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineType");

                    b.Navigation("System");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineTypeMonitoringAttribute", b =>
                {
                    b.HasOne("Graduation_Project.Data.Models.MachineType", "MachineType")
                        .WithMany("MachineTypeMonitoringAttributes")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Data.Models.MonitoringAttribute", "MonitoringAttribute")
                        .WithMany("MachineTypeMonitoringAttributes")
                        .HasForeignKey("MonitoringAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineType");

                    b.Navigation("MonitoringAttribute");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineTypeResourceConsumptionAttribute", b =>
                {
                    b.HasOne("Graduation_Project.Data.Models.MachineType", "MachineType")
                        .WithMany("MachineTypeResourceConsumptionAttributes")
                        .HasForeignKey("MachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Data.Models.ResourceConsumptionAttribute", "ResourceConsumptionAttribute")
                        .WithMany("MachineTypeResourceConsumptionAttributes")
                        .HasForeignKey("ResourceConsumptionAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineType");

                    b.Navigation("ResourceConsumptionAttribute");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MonitoringData", b =>
                {
                    b.HasOne("Graduation_Project.Data.Models.Machine", "Machine")
                        .WithMany("MonitoringData")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Data.Models.MonitoringAttribute", "MonitoringAttribute")
                        .WithMany("MonitoringData")
                        .HasForeignKey("MonitoringAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("MonitoringAttribute");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.ResourceConsumptionData", b =>
                {
                    b.HasOne("Graduation_Project.Data.Models.Machine", "Machine")
                        .WithMany("ResourceConsumptionData")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Data.Models.ResourceConsumptionAttribute", "ResourceConsumptionAttribute")
                        .WithMany("ResourceConsumptionData")
                        .HasForeignKey("ResourceConsumptionAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("ResourceConsumptionAttribute");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.Machine", b =>
                {
                    b.Navigation("MonitoringData");

                    b.Navigation("ResourceConsumptionData");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MachineType", b =>
                {
                    b.Navigation("MachineTypeMonitoringAttributes");

                    b.Navigation("MachineTypeResourceConsumptionAttributes");

                    b.Navigation("Machines");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.MonitoringAttribute", b =>
                {
                    b.Navigation("MachineTypeMonitoringAttributes");

                    b.Navigation("MonitoringData");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.ResourceConsumptionAttribute", b =>
                {
                    b.Navigation("MachineTypeResourceConsumptionAttributes");

                    b.Navigation("ResourceConsumptionData");
                });

            modelBuilder.Entity("Graduation_Project.Data.Models.System", b =>
                {
                    b.Navigation("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
